- name: Create nginx sites-enabled and sites-available directories
  file:
    dest: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - /etc/nginx/sites-available
    - /etc/nginx/sites-enabled

- name: Upload Ghost vhost config
  template:
    src: nginx-ghost.conf.j2
    dest: /etc/nginx/sites-available/{{ nginx.server_name }}.conf
    owner: root
    group: root
    mode: 0644

- name: Upload nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644

- name: Enable the config
  file:
    src: /etc/nginx/sites-available/{{ nginx.server_name }}.conf
    dest: /etc/nginx/sites-enabled/{{ nginx.server_name }}.conf
    state: link
    owner: root
    group: root
    mode: 0644
  notify: restart nginx
