- name: firewalld - Ensure firewalld is running
  service:
    name: firewalld
    state: started
    enabled: yes

- name: firewalld - Enable https and http services
  firewalld:
    zone: public
    service: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  with_items:
    - https
    - http
    - ssh

